const taskTypes = {
  FETCH_TASKS_START: "FETCH_TASKS_START",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILURE: "FETCH_TASKS_FAILURE"
};

export enum TaskType {
  FETCH_TASKS_START = "FETCH_TASKS_START",
  FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE",
  DELETE_TASK = "DELETE_TASK"
}

export default taskTypes;
